repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=1000"]
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    -   id: black
        args: []
        files: .
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        args: []
        files: .
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        args: []
        files: .
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.18.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: local
    hooks:
    -   id: clean
        name: clean
        entry: make
        args: ["clean"]
        language: system
        pass_filenames: false

ci:
    autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
    autoupdate_commit_msg: "[pre-commit.ci] pre-commit-config update"