seed: 1234

trainer:
  gpus: 0
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  fast_dev_run: false
  max_epochs: 30
  min_epochs: 1
  num_sanity_val_steps: 0
  auto_lr_find: false
  checkpoint_callback: true

callbacks:
  model_checkpoint:
    save_top_k: 1
    save_weights_only: true
    mode: "min"
    monitor: "val/loss"
    filename: "{epoch}-{val/loss:.2f}"
  early_stopping:
    patience: 10
    mode: "min"
    monitor: "val/loss"
  learning_rate_monitor:
    logging_interval: "epoch"
    log_momentum: false

data:
  batch_size: 8
  num_workers: 0
  pin_memory: false

lit_model:
  # Optimizer
  lr: 0.001
  weight_decay: 0.0001
  # Scheduler
  mode: "min"
  monitor: "val/loss"
  factor: 0.5
  patience: 3
  # Model
  d_model: 256
  dim_feedforward: 512
  nhead: 2
  dropout: 0.5
  num_decoder_layers: 2
  max_output_len: 150

logger:
  project: "image-to-latex"